on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get latest
        run: |
          echo "sha is $GITHUB_SHA and updated ref is $GITHUB_REF"
